export const irregularVerbs = [
    { 'infinitive': "Arise", 'pastSimple': "arose", 'pastParticiple': "arisen", 'french': "survenir" },
    { 'infinitive': "Awake", 'pastSimple': "awoke", 'pastParticiple': "awoken", 'french': "se réveiller" },
    { 'infinitive': "Be", 'pastSimple': "was / were", 'pastParticiple': "been", 'french': "être " },
    { 'infinitive': "Bear", 'pastSimple': "bore", 'pastParticiple': "borne, born", 'french': "porter, supporter" },
    { 'infinitive': "Beat", 'pastSimple': "beat", 'pastParticiple': "beaten", 'french': "battre, vaincre" },
    { 'infinitive': "Become", 'pastSimple': "became", 'pastParticiple': "become", 'french': "devenir" },
    { 'infinitive': "Beget", 'pastSimple': "begat, begot", 'pastParticiple': "begotten", 'french': "engendrer, causer" },
    { 'infinitive': "Begin", 'pastSimple': "began", 'pastParticiple': "begun", 'french': "commencer, débuter" },
    { 'infinitive': "Bend", 'pastSimple': "bent", 'pastParticiple': "bent", 'french': "plier, se courber, fléchir" },
    { 'infinitive': "Bereave", 'pastSimple': "bereft, bereaved", 'pastParticiple': "bereft, bereaved", 'french': "déposséder, priver" },
    { 'infinitive': "Bet", 'pastSimple': "bet", 'pastParticiple': "bet", 'french': "parier, miser" },
    { 'infinitive': "Bid", 'pastSimple': "bid, bade", 'pastParticiple': "bid, bidden", 'french': "offrir (faire une offre)" },
    { 'infinitive': "Bite", 'pastSimple': "bit", 'pastParticiple': "bitten", 'french': "mordre, piquer (moustique)" },
    { 'infinitive': "Bleed", 'pastSimple': "bled", 'pastParticiple': "bled", 'french': "saigner" },
    { 'infinitive': "Blow", 'pastSimple': "blew", 'pastParticiple': "blown", 'french': "souffler, gonfler" },
    { 'infinitive': "Break", 'pastSimple': "broke", 'pastParticiple': "broken", 'french': "casser, rompre, briser" },
    { 'infinitive': "Breed", 'pastSimple': "bred", 'pastParticiple': "bred", 'french': "élever (animaux)" },
    { 'infinitive': "Bring", 'pastSimple': "brought", 'pastParticiple': "brought", 'french': "apporter, amener" },
    { 'infinitive': "Broadcast", 'pastSimple': "broadcast", 'pastParticiple': "broadcast", 'french': "diffuser, émettre" },
    { 'infinitive': "Build", 'pastSimple': "built", 'pastParticiple': "built", 'french': "construire" },
    { 'infinitive': "Burn", 'pastSimple': "burnt, burned", 'pastParticiple': "burnt, burned", 'french': "brûler" },
    { 'infinitive': "Burst", 'pastSimple': "burst", 'pastParticiple': "burst", 'french': "éclater" },
    { 'infinitive': "Buy", 'pastSimple': "bought", 'pastParticiple': "bought", 'french': "acheter" },
    { 'infinitive': "Can", 'pastSimple': "could", 'pastParticiple': "could", 'french': "pouvoir (verbe modal)" },
    { 'infinitive': "Cast", 'pastSimple': "cast", 'pastParticiple': "cast", 'french': "jeter, distribuer (des rôles)" },
    { 'infinitive': "Catch", 'pastSimple': "caught", 'pastParticiple': "caught", 'french': "attraper" },
    { 'infinitive': "Chide", 'pastSimple': "chid", 'pastParticiple': "chiden", 'french': "gronder, blâmer, réprimander" },
    { 'infinitive': "Choose", 'pastSimple': "chose", 'pastParticiple': "chosen", 'french': "choisir" },
    { 'infinitive': "Cling", 'pastSimple': "clung", 'pastParticiple': "clung", 'french': "s’accrocher" },
    { 'infinitive': "Clothe", 'pastSimple': "clad, clothed", 'pastParticiple': "clad, clothed", 'french': "habiller, recouvrir" },
    { 'infinitive': "Come", 'pastSimple': "came", 'pastParticiple': "come", 'french': "venir" },
    { 'infinitive': "Cost", 'pastSimple': "cost", 'pastParticiple': "cost", 'french': "coûter" },
    { 'infinitive': "Creep", 'pastSimple': "crept", 'pastParticiple': "crept", 'french': "ramper" },
    { 'infinitive': "Cut", 'pastSimple': "cut", 'pastParticiple': "cut", 'french': "couper" },
    { 'infinitive': "Deal", 'pastSimple': "dealt", 'pastParticiple': "dealt", 'french': "distribuer, gérer, dealer" },
    { 'infinitive': "Dig", 'pastSimple': "dug", 'pastParticiple': "dug", 'french': "creuser, extraire du sol" },
    { 'infinitive': "Dive", 'pastSimple': "dived, dove", 'pastParticiple': "dived", 'french': "plonger" },
    { 'infinitive': "Do", 'pastSimple': "did", 'pastParticiple': "done", 'french': "faire (verbe auxiliaire)" },
    { 'infinitive': "Draw", 'pastSimple': "drew", 'pastParticiple': "drawn", 'french': "dessiner, tracer, tirer de" },
    { 'infinitive': "Dream", 'pastSimple': "dreamt, dreamed", 'pastParticiple': "dreamt, dreamed", 'french': "rêver" },
    { 'infinitive': "Drink", 'pastSimple': "drank", 'pastParticiple': "drunk", 'french': "boire" },
    { 'infinitive': "Drive", 'pastSimple': "drove", 'pastParticiple': "driven", 'french': "conduire, propulser" },
    { 'infinitive': "Dwell", 'pastSimple': "dwelt", 'pastParticiple': "dwelt, dwelled", 'french': "habiter, demeurer, résider" },
    { 'infinitive': "Eat", 'pastSimple': "ate", 'pastParticiple': "eaten", 'french': "manger" },
    { 'infinitive': "Fall", 'pastSimple': "fell", 'pastParticiple': "fallen", 'french': "tomber, chuter, diminuer" },
    { 'infinitive': "Feed", 'pastSimple': "fed", 'pastParticiple': "fed", 'french': "nourrir, alimenter" },
    { 'infinitive': "Feel", 'pastSimple': "felt", 'pastParticiple': "felt", 'french': "(se) sentir, ressentir" },
    { 'infinitive': "Fight", 'pastSimple': "fought", 'pastParticiple': "fought", 'french': "se battre, lutter" },
    { 'infinitive': "Find", 'pastSimple': "found", 'pastParticiple': "found", 'french': "trouver" },
    { 'infinitive': "Flee", 'pastSimple': "fled", 'pastParticiple': "fled", 'french': "fuir" },
    { 'infinitive': "Fling", 'pastSimple': "flung", 'pastParticiple': "flung", 'french': "lancer, jeter" },
    { 'infinitive': "Fly", 'pastSimple': "flew", 'pastParticiple': "flown", 'french': "voler (dans les airs)" },
    { 'infinitive': "Forbid", 'pastSimple': "forbade", 'pastParticiple': "forbidden", 'french': "interdire, proscrire" },
    { 'infinitive': "Foresee", 'pastSimple': "foresaw", 'pastParticiple': "foreseen", 'french': "prévoir, pressentir" },
    { 'infinitive': "Forgive", 'pastSimple': "forgave", 'pastParticiple': "forgiven", 'french': "pardonner" },
    { 'infinitive': "Forsake", 'pastSimple': "forsook", 'pastParticiple': "forsaken", 'french': "abandonner, renoncer à" },
    { 'infinitive': "Freeze", 'pastSimple': "froze", 'pastParticiple': "frozen", 'french': "geler" },
    { 'infinitive': "Get", 'pastSimple': "got", 'pastParticiple': "got, gotten", 'french': "obtenir, recevoir, devenir" },
    { 'infinitive': "Give", 'pastSimple': "gave", 'pastParticiple': "given", 'french': "donner" },
    { 'infinitive': "Go", 'pastSimple': "went", 'pastParticiple': "gone", 'french': "aller" },
    { 'infinitive': "Grow", 'pastSimple': "grew", 'pastParticiple': "grown", 'french': "croître, grandir" },
    { 'infinitive': "Hang", 'pastSimple': "hung", 'pastParticiple': "hung", 'french': "pendre" },
    { 'infinitive': "Have", 'pastSimple': "had", 'pastParticiple': "had", 'french': "avoir" },
    { 'infinitive': "Hear", 'pastSimple': "heard", 'pastParticiple': "heard", 'french': "entendre" },
    { 'infinitive': "Hide", 'pastSimple': "hid", 'pastParticiple': "hidden", 'french': "cacher" },
    { 'infinitive': "Hit", 'pastSimple': "hit", 'pastParticiple': "hit", 'french': "frapper" },
    { 'infinitive': "Hold", 'pastSimple': "held", 'pastParticiple': "held", 'french': "tenir" },
    { 'infinitive': "Hurt", 'pastSimple': "hurt", 'pastParticiple': "hurt", 'french': "blesser" },
    { 'infinitive': "Keep", 'pastSimple': "kept", 'pastParticiple': "kept", 'french': "garder, conserver" },
    { 'infinitive': "Kneel", 'pastSimple': "knelt", 'pastParticiple': "knelt", 'french': "s'agenouiller" },
    { 'infinitive': "Knit", 'pastSimple': "knit, knitted", 'pastParticiple': "knit, knitted", 'french': "tricoter" },
    { 'infinitive': "Know", 'pastSimple': "knew", 'pastParticiple': "known", 'french': "savoir, connaître" },
    { 'infinitive': "Lay", 'pastSimple': "laid", 'pastParticiple': "laid", 'french': "poser, coucher" },
    { 'infinitive': "Lead", 'pastSimple': "led", 'pastParticiple': "led", 'french': "conduire, diriger" },
    { 'infinitive': "Leap", 'pastSimple': "leapt", 'pastParticiple': "leapt", 'french': "sauter" },
    { 'infinitive': "Learn", 'pastSimple': "learnt, learned", 'pastParticiple': "learnt, learned", 'french': "apprendre" },
    { 'infinitive': "Leave", 'pastSimple': "left", 'pastParticiple': "left", 'french': "partir, laisser" },
    { 'infinitive': "Lend", 'pastSimple': "lent", 'pastParticiple': "lent", 'french': "prêter" },
    { 'infinitive': "Let", 'pastSimple': "let", 'pastParticiple': "let", 'french': "laisser" },
    { 'infinitive': "Lie", 'pastSimple': "lay", 'pastParticiple': "lain", 'french': "être allongé, mentir" },
    { 'infinitive': "Light", 'pastSimple': "lit, lighted", 'pastParticiple': "lit, lighted", 'french': "éclairer, allumer" },
    { 'infinitive': "Lose", 'pastSimple': "lost", 'pastParticiple': "lost", 'french': "perdre" },
    { 'infinitive': "Make", 'pastSimple': "made", 'pastParticiple': "made", 'french': "faire, fabriquer" },
    { 'infinitive': "Mean", 'pastSimple': "meant", 'pastParticiple': "meant", 'french': "signifier, vouloir dire" },
    { 'infinitive': "Meet", 'pastSimple': "met", 'pastParticiple': "met", 'french': "rencontrer" },
    { 'infinitive': "Melt", 'pastSimple': "melted", 'pastParticiple': "melted", 'french': "fondre" },
    { 'infinitive': "Mistake", 'pastSimple': "mistook", 'pastParticiple': "mistaken", 'french': "commettre une erreur" },
    { 'infinitive': "Mow", 'pastSimple': "mowed", 'pastParticiple': "mown", 'french': "tondre" },
    { 'infinitive': "Overcome", 'pastSimple': "overcame", 'pastParticiple': "overcome", 'french': "surmonter" },
    { 'infinitive': "Overtake", 'pastSimple': "overtook", 'pastParticiple': "overtaken", 'french': "doubler, dépasser" },
    { 'infinitive': "Pay", 'pastSimple': "paid", 'pastParticiple': "paid", 'french': "payer" },
    { 'infinitive': "Put", 'pastSimple': "put", 'pastParticiple': "put", 'french': "mettre" },
    { 'infinitive': "Quit", 'pastSimple': "quit", 'pastParticiple': "quit", 'french': "abandonner, quitter" },
    { 'infinitive': "Read", 'pastSimple': "read", 'pastParticiple': "read", 'french': "lire" },
    { 'infinitive': "Ride", 'pastSimple': "rode", 'pastParticiple': "ridden", 'french': "monter (vélo, cheval)" },
    { 'infinitive': "Ring", 'pastSimple': "rang", 'pastParticiple': "rung", 'french': "sonner" },
    { 'infinitive': "Rise", 'pastSimple': "rose", 'pastParticiple': "risen", 'french': "s'élever, se lever" },
    { 'infinitive': "Run", 'pastSimple': "ran", 'pastParticiple': "run", 'french': "courir" },
    { 'infinitive': "Saw", 'pastSimple': "sawed", 'pastParticiple': "sawn", 'french': "scier" },
    { 'infinitive': "Say", 'pastSimple': "said", 'pastParticiple': "said", 'french': "dire" },
    { 'infinitive': "See", 'pastSimple': "saw", 'pastParticiple': "seen", 'french': "voir" },
    { 'infinitive': "Sell", 'pastSimple': "sold", 'pastParticiple': "sold", 'french': "vendre" },
    { 'infinitive': "Send", 'pastSimple': "sent", 'pastParticiple': "sent", 'french': "envoyer" },
    { 'infinitive': "Set", 'pastSimple': "set", 'pastParticiple': "set", 'french': "mettre, poser" },
    { 'infinitive': "Shake", 'pastSimple': "shook", 'pastParticiple': "shaken", 'french': "secouer" },
    { 'infinitive': "Shine", 'pastSimple': "shone", 'pastParticiple': "shone", 'french': "briller" },
    { 'infinitive': "Shoot", 'pastSimple': "shot", 'pastParticiple': "shot", 'french': "tirer" },
    { 'infinitive': "Show", 'pastSimple': "showed", 'pastParticiple': "shown", 'french': "montrer" },
    { 'infinitive': "Shrink", 'pastSimple': "shrank", 'pastParticiple': "shrunk", 'french': "rétrécir" },
    { 'infinitive': "Shut", 'pastSimple': "shut", 'pastParticiple': "shut", 'french': "fermer" },
    { 'infinitive': "Sing", 'pastSimple': "sang", 'pastParticiple': "sung", 'french': "chanter" },
    { 'infinitive': "Sink", 'pastSimple': "sank", 'pastParticiple': "sunk", 'french': "couler" },
    { 'infinitive': "Sit", 'pastSimple': "sat", 'pastParticiple': "sat", 'french': "s'asseoir" },
    { 'infinitive': "Sleep", 'pastSimple': "slept", 'pastParticiple': "slept", 'french': "dormir" },
    { 'infinitive': "Slide", 'pastSimple': "slid", 'pastParticiple': "slid", 'french': "glisser" },
    { 'infinitive': "Smell", 'pastSimple': "smelt", 'pastParticiple': "smelt", 'french': "sentir" },
    { 'infinitive': "Speak", 'pastSimple': "spoke", 'pastParticiple': "spoken", 'french': "parler" },
    { 'infinitive': "Speed", 'pastSimple': "sped", 'pastParticiple': "sped", 'french': "accélérer" },
    { 'infinitive': "Spend", 'pastSimple': "spent", 'pastParticiple': "spent", 'french': "dépenser, passer (du temps)" },
    { 'infinitive': "Spin", 'pastSimple': "spun", 'pastParticiple': "spun", 'french': "tourner, filer" },
    { 'infinitive': "Spit", 'pastSimple': "spat", 'pastParticiple': "spat", 'french': "cracher" },
    { 'infinitive': "Split", 'pastSimple': "split", 'pastParticiple': "split", 'french': "diviser" },
    { 'infinitive': "Spread", 'pastSimple': "spread", 'pastParticiple': "spread", 'french': "répandre" },
    { 'infinitive': "Spring", 'pastSimple': "sprang", 'pastParticiple': "sprung", 'french': "jaillir" },
    { 'infinitive': "Stand", 'pastSimple': "stood", 'pastParticiple': "stood", 'french': "se tenir debout" },
    { 'infinitive': "Steal", 'pastSimple': "stole", 'pastParticiple': "stolen", 'french': "voler" },
    { 'infinitive': "Stick", 'pastSimple': "stuck", 'pastParticiple': "stuck", 'french': "coller, enfoncer" },
    { 'infinitive': "Strike", 'pastSimple': "struck", 'pastParticiple': "struck", 'french': "frapper" },
    { 'infinitive': "Swear", 'pastSimple': "swore", 'pastParticiple': "sworn", 'french': "jurer" },
    { 'infinitive': "Swim", 'pastSimple': "swam", 'pastParticiple': "swum", 'french': "nager" },
    { 'infinitive': "Take", 'pastSimple': "took", 'pastParticiple': "taken", 'french': "prendre" },
    { 'infinitive': "Teach", 'pastSimple': "taught", 'pastParticiple': "taught", 'french': "enseigner" },
    { 'infinitive': "Tear", 'pastSimple': "tore", 'pastParticiple': "torn", 'french': "déchirer" },
    { 'infinitive': "Tell", 'pastSimple': "told", 'pastParticiple': "told", 'french': "dire, raconter" },
    { 'infinitive': "Think", 'pastSimple': "thought", 'pastParticiple': "thought", 'french': "penser" },
    { 'infinitive': "Throw", 'pastSimple': "threw", 'pastParticiple': "thrown", 'french': "jeter" },
    { 'infinitive': "Understand", 'pastSimple': "understood", 'pastParticiple': "understood", 'french': "comprendre" },
    { 'infinitive': "Wake", 'pastSimple': "woke", 'pastParticiple': "woken", 'french': "réveiller" },
    { 'infinitive': "Wear", 'pastSimple': "wore", 'pastParticiple': "worn", 'french': "porter (vêtements)" },
    { 'infinitive': "Win", 'pastSimple': "won", 'pastParticiple': "won", 'french': "gagner" },
    { 'infinitive': "Write", 'pastSimple': "wrote", 'pastParticiple': "written", 'french': "écrire" }
]